#!/bin/sh

# Xcode Cloud에서 Flutter 빌드를 위한 post-clone 스크립트

set -e

echo "=========================================="
echo "=== Xcode Cloud Flutter 빌드 준비 시작 ==="
echo "=========================================="

# 프로젝트 디렉토리 설정
if [ -n "$CI_PRIMARY_REPOSITORY_PATH" ]; then
    PROJECT_PATH="$CI_PRIMARY_REPOSITORY_PATH/apps/mobile"
else
    PROJECT_PATH="$(cd "$(dirname "$0")/../.." && pwd)"
fi

echo "프로젝트 경로: $PROJECT_PATH"

# ===========================================
# 1. .env 파일 생성 (Xcode Cloud 환경 변수에서)
# ===========================================
echo ""
echo "=== 1. .env 파일 생성 ==="

ENV_FILE="$PROJECT_PATH/.env"

cat > "$ENV_FILE" << EOF
# ============================================
# 모두의수선 - Flutter Mobile 환경변수
# Generated by Xcode Cloud ci_post_clone.sh
# ============================================

# Supabase Project URL
SUPABASE_URL=${SUPABASE_URL:-https://rzrwediccbamxluegnex.supabase.co}

# Supabase Anon Key (Public API Key)
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6cndlZGljY2JhbXhsdWVnbmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MzY0NDUsImV4cCI6MjA3ODUxMjQ0NX0.FhehjJfpXDhIwOCn6Raq0wJ4TQ8TiT3AR2F_pS5XUYY}

# Supabase Service Role Key (서버 사이드에서만 사용)
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}

# Cloudflare Stream
CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID:-7ff4ad7c491689d45062a2bedd9af2e0}
CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN=${CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN:-wn4smwc3lzqmm79i}

# 우체국 API (선택사항)
EPOST_API_KEY=${EPOST_API_KEY:-}
EPOST_CUSTOMER_ID=${EPOST_CUSTOMER_ID:-}

# 네이버 로그인
NAVER_CLIENT_ID=${NAVER_CLIENT_ID:-b7QJILomSlfsFL7RuAQs}
NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET:-}
NAVER_CLIENT_NAME=${NAVER_CLIENT_NAME:-모두의수선}
EOF

echo ".env 파일 생성 완료: $ENV_FILE"

# ===========================================
# 2. Flutter SDK 설치
# ===========================================
FLUTTER_SDK_DIR="$HOME/flutter"
FLUTTER_VERSION="3.32.2"

echo ""
echo "=== 2. Flutter SDK 설치 ==="

if [ -d "$FLUTTER_SDK_DIR" ]; then
    echo "Flutter SDK가 이미 존재합니다"
else
    echo "Flutter SDK 다운로드 중... (버전: $FLUTTER_VERSION)"
    git clone https://github.com/flutter/flutter.git -b "$FLUTTER_VERSION" "$FLUTTER_SDK_DIR"
    echo "Flutter SDK 다운로드 완료"
fi

export PATH="$FLUTTER_SDK_DIR/bin:$PATH"

# Flutter precache 실행
echo ""
echo "=== 3. Flutter precache ==="
flutter precache --ios

echo ""
echo "=== 4. Flutter 버전 확인 ==="
flutter --version

# 프로젝트 디렉토리로 이동
cd "$PROJECT_PATH"

echo ""
echo "=== 5. Flutter 패키지 설치 ==="
flutter pub get

echo ""
echo "=== 6. iOS 빌드 준비 ==="
flutter build ios --config-only --release --no-codesign

echo ""
echo "=== 7. CocoaPods 설치 ==="
cd ios
pod install --repo-update

echo ""
echo "=========================================="
echo "=== 빌드 준비 완료 ==="
echo "=========================================="
