#!/bin/sh

# Xcode Cloud에서 Flutter 빌드를 위한 post-clone 스크립트

set -e

echo "=========================================="
echo "=== Xcode Cloud Flutter 빌드 준비 시작 ==="
echo "=========================================="

# 프로젝트 디렉토리 설정
if [ -n "$CI_PRIMARY_REPOSITORY_PATH" ]; then
    PROJECT_PATH="$CI_PRIMARY_REPOSITORY_PATH/apps/mobile"
else
    PROJECT_PATH="$(cd "$(dirname "$0")/../.." && pwd)"
fi

echo "프로젝트 경로: $PROJECT_PATH"

# ===========================================
# 1. .env 파일 생성 (Xcode Cloud 환경 변수에서)
# ===========================================
echo ""
echo "=== 1. .env 파일 생성 ==="

ENV_FILE="$PROJECT_PATH/.env"

cat > "$ENV_FILE" << EOF
# ============================================
# 모두의수선 - Flutter Mobile 환경변수
# Generated by Xcode Cloud ci_post_clone.sh
# ============================================

# Supabase Project URL
SUPABASE_URL=${SUPABASE_URL:-https://rzrwediccbamxluegnex.supabase.co}

# Supabase Anon Key (Public API Key)
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6cndlZGljY2JhbXhsdWVnbmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MzY0NDUsImV4cCI6MjA3ODUxMjQ0NX0.FhehjJfpXDhIwOCn6Raq0wJ4TQ8TiT3AR2F_pS5XUYY}

# Supabase Service Role Key (서버 사이드에서만 사용)
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}

# Cloudflare Stream
CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID:-7ff4ad7c491689d45062a2bedd9af2e0}
CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN=${CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN:-wn4smwc3lzqmm79i}

# 우체국 API (선택사항)
EPOST_API_KEY=${EPOST_API_KEY:-}
EPOST_CUSTOMER_ID=${EPOST_CUSTOMER_ID:-}

# 네이버 로그인
NAVER_CLIENT_ID=${NAVER_CLIENT_ID:-b7QJILomSlfsFL7RuAQs}
NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET:-}
NAVER_CLIENT_NAME=${NAVER_CLIENT_NAME:-모두의수선}
EOF

echo ".env 파일 생성 완료: $ENV_FILE"

# ===========================================
# 2. Flutter SDK 설치
# pubspec.lock sdks.flutter (>=3.35.0)와 동일 계열로 핀
#
# Xcode Cloud에서 GCS zip(curl 35 SSL)과 git 캐시/태그 전환이
# 각각 깨질 수 있어:
#  1) 핀 일치 시 캐시 재사용
#  2) 아니면 클린 git shallow clone (캐시에서 checkout 하지 않음)
#  3) git 실패 시 공식 zip (HTTP/1.1 + 재시도)
# ===========================================
FLUTTER_SDK_DIR="$HOME/flutter"
FLUTTER_VERSION="3.35.7"
FLUTTER_PIN_FILE="$FLUTTER_SDK_DIR/.ci_pin_version"
FLUTTER_RELEASE_BASE="https://storage.googleapis.com/flutter_infra_release/releases"

echo ""
echo "=== 2. Flutter SDK 설치 ==="

mark_flutter_pin() {
    echo "$FLUTTER_VERSION" > "$FLUTTER_PIN_FILE"
}

install_flutter_via_git() {
    echo "Flutter SDK git clone 중... (버전: $FLUTTER_VERSION)"
    rm -rf "$FLUTTER_SDK_DIR"
    # 캐시된 SDK에서 fetch/checkout 하지 않음 — 클린 shallow clone만 사용
    # set -e 하에서도 폴백 가능하도록 || return 사용
    git clone https://github.com/flutter/flutter.git \
        -b "$FLUTTER_VERSION" --depth 1 "$FLUTTER_SDK_DIR" || {
        echo "❌ Flutter git clone 실패"
        return 1
    }
    if [ ! -x "$FLUTTER_SDK_DIR/bin/flutter" ]; then
        echo "❌ Flutter git clone 실패: bin/flutter 없음"
        return 1
    fi
    mark_flutter_pin
    echo "Flutter SDK git clone 완료"
    return 0
}

install_flutter_via_zip() {
    ARCH="$(uname -m)"
    if [ "$ARCH" = "arm64" ]; then
        ARCHIVE="stable/macos/flutter_macos_arm64_${FLUTTER_VERSION}-stable.zip"
    else
        ARCHIVE="stable/macos/flutter_macos_${FLUTTER_VERSION}-stable.zip"
    fi

    echo "Flutter SDK zip 다운로드 중... (버전: $FLUTTER_VERSION, arch: $ARCH)"
    echo "URL: $FLUTTER_RELEASE_BASE/$ARCHIVE"

    rm -rf "$FLUTTER_SDK_DIR"
    TMP_ZIP="$HOME/flutter_sdk_${FLUTTER_VERSION}.zip"
    rm -f "$TMP_ZIP"

    # Xcode Cloud에서 HTTP/2 + GCS SSL handshake(curl 35)가 간헐 실패함
    # --http1.1 / --retry-all-errors 로 완화. zip은 ~2GB라 시간 여유 필요.
    CURL_STATUS=0
    curl -fL --http1.1 \
        --connect-timeout 60 \
        --max-time 1200 \
        --retry 5 \
        --retry-delay 5 \
        --retry-all-errors \
        -o "$TMP_ZIP" \
        "$FLUTTER_RELEASE_BASE/$ARCHIVE" || CURL_STATUS=$?
    if [ "$CURL_STATUS" -ne 0 ]; then
        echo "❌ Flutter zip 다운로드 실패 (curl exit $CURL_STATUS)"
        rm -f "$TMP_ZIP"
        return 1
    fi

    # zip 루트는 flutter/ 디렉터리
    unzip -q "$TMP_ZIP" -d "$HOME" || {
        echo "❌ Flutter zip 압축 해제 실패"
        rm -f "$TMP_ZIP"
        return 1
    }
    rm -f "$TMP_ZIP"

    if [ ! -x "$FLUTTER_SDK_DIR/bin/flutter" ]; then
        echo "❌ Flutter SDK 압축 해제 실패: $FLUTTER_SDK_DIR/bin/flutter 없음"
        return 1
    fi

    mark_flutter_pin
    echo "Flutter SDK zip 설치 완료"
    return 0
}

install_flutter_sdk() {
    if install_flutter_via_git; then
        return 0
    fi
    echo "git clone 실패 — 공식 zip으로 폴백"
    if install_flutter_via_zip; then
        return 0
    fi
    echo "❌ Flutter SDK 설치 실패 (git + zip 모두 실패)"
    exit 1
}

CACHED_PIN=""
if [ -f "$FLUTTER_PIN_FILE" ]; then
    CACHED_PIN="$(cat "$FLUTTER_PIN_FILE" 2>/dev/null || true)"
fi

if [ "$CACHED_PIN" = "$FLUTTER_VERSION" ] && [ -x "$FLUTTER_SDK_DIR/bin/flutter" ]; then
    echo "캐시된 Flutter SDK 사용: $FLUTTER_VERSION"
else
    if [ -d "$FLUTTER_SDK_DIR" ]; then
        echo "캐시된 Flutter($CACHED_PIN)가 핀($FLUTTER_VERSION)과 다름 — 클린 재설치"
    fi
    install_flutter_sdk
fi

export PATH="$FLUTTER_SDK_DIR/bin:$PATH"
flutter config --no-analytics >/dev/null 2>&1 || true
flutter --version

# --machine JSON으로 버전 확인 (부트스트랩 로그에 흔들리지 않음)
RESOLVED_VERSION="$(
    flutter --version --machine 2>/dev/null \
      | python3 -c 'import sys,json; print(json.load(sys.stdin).get("frameworkVersion",""))' \
      2>/dev/null || true
)"
if [ -z "$RESOLVED_VERSION" ]; then
    # python3 파싱 실패 시 pin 파일로 대체 확인
    RESOLVED_VERSION="$(cat "$FLUTTER_PIN_FILE" 2>/dev/null || true)"
fi
if [ "$RESOLVED_VERSION" != "$FLUTTER_VERSION" ]; then
    echo "❌ Flutter 버전 불일치: expected $FLUTTER_VERSION, got $RESOLVED_VERSION"
    exit 1
fi
echo "✅ Flutter 버전 확인: $RESOLVED_VERSION"

# Flutter precache 실행
echo ""
echo "=== 3. Flutter precache ==="
flutter precache --ios

echo ""
echo "=== 4. Flutter 버전 확인 ==="
flutter --version

# 프로젝트 디렉토리로 이동
cd "$PROJECT_PATH"

echo ""
echo "=== 5. Flutter 패키지 설치 ==="
flutter pub get

echo ""
echo "=== 6. iOS 빌드 준비 ==="
flutter build ios --config-only --release --no-codesign

echo ""
echo "=== 7. CocoaPods 설치 ==="
cd ios
pod install --repo-update

echo ""
echo "=========================================="
echo "=== 빌드 준비 완료 ==="
echo "=========================================="
