#!/bin/sh

# Xcode Cloud에서 Flutter 빌드를 위한 post-clone 스크립트

set -e

echo "=========================================="
echo "=== Xcode Cloud Flutter 빌드 준비 시작 ==="
echo "=========================================="

# 프로젝트 디렉토리 설정
if [ -n "$CI_PRIMARY_REPOSITORY_PATH" ]; then
    PROJECT_PATH="$CI_PRIMARY_REPOSITORY_PATH/apps/mobile"
else
    PROJECT_PATH="$(cd "$(dirname "$0")/../.." && pwd)"
fi

echo "프로젝트 경로: $PROJECT_PATH"

# ===========================================
# 1. .env 파일 생성 (Xcode Cloud 환경 변수에서)
# ===========================================
echo ""
echo "=== 1. .env 파일 생성 ==="

ENV_FILE="$PROJECT_PATH/.env"

cat > "$ENV_FILE" << EOF
# ============================================
# 모두의수선 - Flutter Mobile 환경변수
# Generated by Xcode Cloud ci_post_clone.sh
# ============================================

# Supabase Project URL
SUPABASE_URL=${SUPABASE_URL:-https://rzrwediccbamxluegnex.supabase.co}

# Supabase Anon Key (Public API Key)
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6cndlZGljY2JhbXhsdWVnbmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MzY0NDUsImV4cCI6MjA3ODUxMjQ0NX0.FhehjJfpXDhIwOCn6Raq0wJ4TQ8TiT3AR2F_pS5XUYY}

# Supabase Service Role Key (서버 사이드에서만 사용)
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}

# Cloudflare Stream
CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID:-7ff4ad7c491689d45062a2bedd9af2e0}
CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN=${CLOUDFLARE_STREAM_CUSTOMER_SUBDOMAIN:-wn4smwc3lzqmm79i}

# 우체국 API (선택사항)
EPOST_API_KEY=${EPOST_API_KEY:-}
EPOST_CUSTOMER_ID=${EPOST_CUSTOMER_ID:-}

# 네이버 로그인
NAVER_CLIENT_ID=${NAVER_CLIENT_ID:-b7QJILomSlfsFL7RuAQs}
NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET:-}
NAVER_CLIENT_NAME=${NAVER_CLIENT_NAME:-모두의수선}
EOF

echo ".env 파일 생성 완료: $ENV_FILE"

# ===========================================
# 2. Flutter SDK 설치
# pubspec.lock sdks.flutter (>=3.35.0)와 동일 계열로 핀
# git shallow clone는 Xcode Cloud에서 캐시/태그 전환이 자주 깨지므로
# 공식 stable macOS zip을 사용한다.
# ===========================================
FLUTTER_SDK_DIR="$HOME/flutter"
FLUTTER_VERSION="3.35.7"
FLUTTER_PIN_FILE="$FLUTTER_SDK_DIR/.ci_pin_version"
FLUTTER_RELEASE_BASE="https://storage.googleapis.com/flutter_infra_release/releases"

echo ""
echo "=== 2. Flutter SDK 설치 ==="

install_flutter_sdk() {
    ARCH="$(uname -m)"
    if [ "$ARCH" = "arm64" ]; then
        ARCHIVE="stable/macos/flutter_macos_arm64_${FLUTTER_VERSION}-stable.zip"
    else
        ARCHIVE="stable/macos/flutter_macos_${FLUTTER_VERSION}-stable.zip"
    fi

    echo "Flutter SDK 다운로드 중... (버전: $FLUTTER_VERSION, arch: $ARCH)"
    echo "URL: $FLUTTER_RELEASE_BASE/$ARCHIVE"

    rm -rf "$FLUTTER_SDK_DIR"
    TMP_ZIP="$HOME/flutter_sdk_${FLUTTER_VERSION}.zip"
    rm -f "$TMP_ZIP"

    curl -fL --retry 3 --retry-delay 2 \
        -o "$TMP_ZIP" \
        "$FLUTTER_RELEASE_BASE/$ARCHIVE"

    # zip 루트는 flutter/ 디렉터리
    unzip -q "$TMP_ZIP" -d "$HOME"
    rm -f "$TMP_ZIP"

    if [ ! -x "$FLUTTER_SDK_DIR/bin/flutter" ]; then
        echo "❌ Flutter SDK 압축 해제 실패: $FLUTTER_SDK_DIR/bin/flutter 없음"
        exit 1
    fi

    echo "$FLUTTER_VERSION" > "$FLUTTER_PIN_FILE"
    echo "Flutter SDK 다운로드 완료"
}

CACHED_PIN=""
if [ -f "$FLUTTER_PIN_FILE" ]; then
    CACHED_PIN="$(cat "$FLUTTER_PIN_FILE" 2>/dev/null || true)"
fi

if [ "$CACHED_PIN" = "$FLUTTER_VERSION" ] && [ -x "$FLUTTER_SDK_DIR/bin/flutter" ]; then
    echo "캐시된 Flutter SDK 사용: $FLUTTER_VERSION"
else
    if [ -d "$FLUTTER_SDK_DIR" ]; then
        echo "캐시된 Flutter($CACHED_PIN)가 핀($FLUTTER_VERSION)과 다름 — 재설치"
    fi
    install_flutter_sdk
fi

export PATH="$FLUTTER_SDK_DIR/bin:$PATH"
flutter config --no-analytics >/dev/null 2>&1 || true
flutter --version

# --machine JSON으로 버전 확인 (부트스트랩 로그에 흔들리지 않음)
RESOLVED_VERSION="$(
    flutter --version --machine 2>/dev/null \
      | python3 -c 'import sys,json; print(json.load(sys.stdin).get("frameworkVersion",""))' \
      2>/dev/null || true
)"
if [ -z "$RESOLVED_VERSION" ]; then
    # python3 파싱 실패 시 pin 파일로 대체 확인
    RESOLVED_VERSION="$(cat "$FLUTTER_PIN_FILE" 2>/dev/null || true)"
fi
if [ "$RESOLVED_VERSION" != "$FLUTTER_VERSION" ]; then
    echo "❌ Flutter 버전 불일치: expected $FLUTTER_VERSION, got $RESOLVED_VERSION"
    exit 1
fi
echo "✅ Flutter 버전 확인: $RESOLVED_VERSION"

# Flutter precache 실행
echo ""
echo "=== 3. Flutter precache ==="
flutter precache --ios

echo ""
echo "=== 4. Flutter 버전 확인 ==="
flutter --version

# 프로젝트 디렉토리로 이동
cd "$PROJECT_PATH"

echo ""
echo "=== 5. Flutter 패키지 설치 ==="
flutter pub get

echo ""
echo "=== 6. iOS 빌드 준비 ==="
flutter build ios --config-only --release --no-codesign

echo ""
echo "=== 7. CocoaPods 설치 ==="
cd ios
pod install --repo-update

echo ""
echo "=========================================="
echo "=== 빌드 준비 완료 ==="
echo "=========================================="
